
server:
  port: 8080
  tomcat:
    max-http-form-post-size: 31457280  # 30MB


# database setting
spring:
  servlet:
    multipart:
      max-file-size: 3MB  # 1?? ??? ?? ??
      max-request-size: 20MB  # 1?? ??? ?? ? ?? ?? ??




  datasource:
    url: jdbc:mariadb://localhost:3306/puppy
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    # DBMS dialect setting
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl ??? ??? ????...
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # SQL ?? ??? ??? ??
    database: mysql

# log level setting
logging:
  level:
    root: info
    com.example.demo: debug
    org.hibernate.SQL: debug



file:
  upload-dir: /Users/hgb926/Desktop/academy-study/puppy-img






